name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
   - uses: secrethub/actions/env-export@v0.2.1
     env:
      GITHUB_CONTEXT: ${{ secrets.FRIBASETOKEN }}
    - name: Dump GitHub context
      run: echo "$GITHUB_CONTEXT"
